### PR TITLE
automation: build and publish Python plugins to PyPI

### LINKED ISSUE #34: Publish Python plugins to PyPI
In order to make Python plugins consumable by tools like [Krkn](https://github.com/redhat-chaos/krkn), the Python plugins should be published to PyPI. We already have a namespace set up, it's only a matter of porting the [SDK publishing process](https://github.com/arcalot/arcaflow-plugin-sdk-python/blob/main/.github/workflows/build.yml) and apply it to the [build process](#2)

### PR DESCRIPTION
**Pull request by sandrobonazzola**
## Changes introduced with this PR

Please explain your changes here.

Fixes #34, taking care of building the project and publishing to the python registry.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by portante** [comment]
Can we consider using `Draft` PRs instead of having `[WIP]` in the title?

**Comment by sandrobonazzola** [comment]
> Can we consider using `Draft` PRs instead of having `[WIP]` in the title?

converted to draft, I would keep [WIP] anyway, make it more clear this is a work still in progress.

**Comment by sandrobonazzola** [comment]
> We can't maintain an ever-growing list if GHA integrations for plugins.

If you don't want to keep testing of the plugins within the global workflow we need to set a workflow file for each plugin, perhaps within the plugin directory itself and have the global workflow iterate over the various plugins.
Each plugin has its own runtime deps and it's supposed to run also as standalone script on the same system where the other plugins are running. I can drop the testing part from this PR and focus only on the build and push to pypi but we need to define a strategy for the plugins testing.

**Comment by sandrobonazzola** [comment]
Going to handle this differently using arcaflow-plugin-image-builder .

**Pull request closed without merging**
